In [1]:
import timecorr
from timecorr import timecorr as tc

In [2]:
import numpy as np
import pandas as pd

In [16]:
test0= np.array([1, 2])
print (test0)

[1 2]


In [18]:
test0.ndim #does not work with 1 dim np.arrays 

1

In [131]:
test1= np.random.randn(10,3)

In [132]:
test1.ndim

2

In [134]:
tctest1= tc(test1)
tctest1.shape

(10, 6)

In [89]:
test2=np.array([[1, 2, 1, 2, 1, 2],[4, 10, 12, 35, 36, 24], [1, 2, 1, 2, 1, 2], [1, 2], [1, 2],[1, 2, 1, 2, 1, 2], [1, 2], [1, 2]])

In [84]:
test2.ndim

2

In [90]:
tctest2=tc(test2)

In [79]:
d = {'col1': [1, 2, 3], 'col2': [3, 4, 9], 'col3': [3, 4, 9]}
test3=pd.DataFrame(data=d)
print(test3)

   col1  col2  col3
0     1     3     3
1     2     4     4
2     3     9     9


In [91]:
tctest3=tc(test3)

In [115]:
df = pd.DataFrame.from_csv("new.csv")
test4=df[1:5]
print(test4)

           AMT.CSV AMN.csv
datefirst                 
2005-02-25  16.846   13.28
2005-02-28    16.6   13.53
2005-03-01  16.912   13.17
2005-03-02  16.846   13.36


/Users/Emily/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  """Entry point for launching an IPython kernel.


In [116]:
tc(test4)

array([[ 0.76124489,  0.76159436,  0.76166459,  0.76166459,  0.76110518,
         0.76236593,  0.76124489, -0.52056217, -0.32141358, -0.32141358,
        -0.32121378, -0.32166384,  0.76124489, -0.52077217, -0.52077217,
         0.52049149,  0.52112388, -0.52056217,  0.76166459, -0.32136387,
        -0.32181208, -0.32141358, -0.32136387, -0.32181208, -0.32141358,
        -0.32161447, -0.32121378, -0.32166384],
       [ 0.76138435,  0.76159437,  0.76152425,  0.76152425,  0.76152425,
         0.7619445 ,  0.76138435, -0.52063197, -0.32141315, -0.32141315,
        -0.32141315, -0.32156296,  0.76138435, -0.52070197, -0.52070197,
         0.52070186,  0.52091266, -0.52063197,  0.76152425, -0.32146297,
        -0.32161258, -0.32141315, -0.32146297, -0.32161258, -0.32141315,
        -0.32161258, -0.32141315, -0.32156296],
       [ 0.76152425,  0.76159437,  0.76138435,  0.76138435,  0.7619445 ,
         0.76152425,  0.76152425, -0.52070197, -0.32141315, -0.32141315,
        -0.32161258, -0.3214

In [127]:
df = pd.read_csv("new.csv")
test8=df[1:5]
print(test8)

    datefirst AMT.CSV AMN.csv
1  2005-02-25  16.846   13.28
2  2005-02-28    16.6   13.53
3  2005-03-01  16.912   13.17
4  2005-03-02  16.846   13.36


In [128]:
tc(test8)

array([[ 0.76110518,  0.76124489,  0.76166459,  0.76236593,  0.76124489,
         0.76159436,  0.76166459,  0.76166459,  0.76110518,  0.76236593,
         0.76124489, -0.32121378, -0.32136387, -0.32161447, -0.32121378,
         0.52049149, -0.32136387, -0.32136387,  0.76110518, -0.32161447,
        -0.32121378, -0.32141358, -0.32166384,  0.76124489, -0.52056217,
        -0.32141358, -0.32141358, -0.32121378, -0.32166384,  0.76124489,
        -0.32181208, -0.32141358, -0.52077217,  0.76166459,  0.76166459,
        -0.32136387, -0.32181208, -0.32141358, -0.32166384,  0.52112388,
        -0.32181208, -0.32181208, -0.32161447,  0.76236593, -0.32166384,
        -0.52056217, -0.32141358, -0.32141358, -0.32121378, -0.32166384,
         0.76124489, -0.52077217, -0.52077217,  0.52049149,  0.52112388,
        -0.52056217,  0.76166459, -0.32136387, -0.32181208, -0.32141358,
        -0.32136387, -0.32181208, -0.32141358, -0.32161447, -0.32121378,
        -0.32166384],
       [ 0.76152425,  0.76138

In [92]:
test5= np.array([[4, 10, 12], [1, 2, 3],[8, 0, 2]])

In [28]:
test6= np.array([[1, 2, 1], [2, 1, 2]])

[[1 2 1]
 [2 1 2]]


In [32]:
test6.ndim

2

In [33]:
test7=np.array([[1, 0, 0],[0,1, 0],[0,0,1]])

In [93]:
tc(test7, mode= 'within')

array([[ 0.76141948,  0.76152427,  0.76183968, -0.4620025 , -0.46215053,
        -0.46219942],
       [ 0.76162917,  0.7615242 ,  0.76162917, -0.46210081, -0.46214993,
        -0.46210081],
       [ 0.76183968,  0.76152427,  0.76141948, -0.46219942, -0.46215053,
        -0.4620025 ]])

In [94]:
tc(test7, mode='across')

array([[ 0.76141948,  0.76152427,  0.76183968, -0.4620025 , -0.46215053,
        -0.46219942],
       [ 0.76162917,  0.7615242 ,  0.76162917, -0.46210081, -0.46214993,
        -0.46210081],
       [ 0.76183968,  0.76152427,  0.76141948, -0.46219942, -0.46215053,
        -0.4620025 ]])

In [129]:
print(test1.shape)
print(test2.shape)
print(test3.shape)
print(test4.shape)
print(test5.shape)
print(test6.shape)
print(test7.shape)
print(test8.shape)

(3, 3)
(4, 2)
(3, 3)
(4, 2)
(3, 3)
(2, 3)
(3, 3)
(4, 3)


In [130]:
print(tc(test1).shape)
print(tc(test2).shape)
print(tc(test3).shape)
print(tc(test4).shape)
print(tc(test5).shape)
print(tc(test6).shape)
print(tc(test7).shape)
print(tc(test8).shape)

(3, 6)
(4, 3)
(3, 6)
(4, 28)
(3, 6)
(2, 6)
(3, 6)
(4, 66)


In [100]:
import matplotlib 
matplotlib.pyplot.matshow(df.corr(tc(test3)))

/Users/Emily/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:5489: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if method == 'pearson':
/Users/Emily/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:5491: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif method == 'spearman':
/Users/Emily/anaconda3/lib/python3.6/site-packages/pandas/core/nanops.py:763: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if method in ['kendall', 'spearman']:


TypeError: unhashable type: 'numpy.ndarray'

In [110]:
import seaborn as sns
corr = df.corr(tc(test3))
sns.heatmap(corr, 
            xticklabels=corr.columns.values,
            yticklabels=corr.columns.values)

/Users/Emily/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:5489: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if method == 'pearson':
/Users/Emily/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:5491: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif method == 'spearman':
/Users/Emily/anaconda3/lib/python3.6/site-packages/pandas/core/nanops.py:763: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if method in ['kendall', 'spearman']:


TypeError: unhashable type: 'numpy.ndarray'