In [8]:
# coding: utf-8

from past.utils import old_div
import numpy as np
import scipy.spatial.distance as sd
from scipy.linalg import toeplitz
import hypertools as hyp
import pandas as pd
gaussian_params = {'var': 1000}


def gaussian_weights(T, params=gaussian_params):
    c1 = np.divide(1, np.sqrt(2 * np.math.pi * params['var']))
    c2 = np.divide(-1, 2 * params['var'])
    sqdiffs = toeplitz(np.arange(T)) ** 2
    return c1 * np.exp(c2 * sqdiffs)




In [23]:
data_list= np.random.randn(10,3)
pandas_dataframe= pd.DataFrame(np.random.randint(low=0, high=10, size=(2, 2)))
numpy_array= np.array([[5, 9], [10, 7], [5, 9]])
numpy_array_list= np.array([[8,2],[4,6]]).tolist()

In [24]:
data_dl = hyp.tools.format_data(data_list)
data_pdf = hyp.tools.format_data(pandas_dataframe)
data_npa = hyp.tools.format_data(numpy_array)

In [25]:
Test_dl=  data_dl[0].shape[0]
Test_pdf=  data_pdf[0].shape[0]
Test_npa=  data_npa[0].shape[0]

In [26]:
dl_tester = gaussian_weights(Test_dl, params=gaussian_params)
pdf_tester = gaussian_weights(Test_pdf, params=gaussian_params)
npa_tester = gaussian_weights(Test_npa, params=gaussian_params)

In [27]:
gaussian_weights(Test_dl, params=gaussian_params).shape

(10, 10)

In [28]:
gaussian_weights(Test_pdf, params=gaussian_params).shape

(2, 2)

In [29]:
gaussian_weights(Test_npa, params=gaussian_params).shape

(3, 3)

In [30]:
type(gaussian_weights(Test_npa, params=gaussian_params))

numpy.ndarray

In [31]:
type(gaussian_weights(Test_pdf, params=gaussian_params))

numpy.ndarray

In [32]:
type(gaussian_weights(Test_dl, params=gaussian_params))

numpy.ndarray

In [33]:
data_list.shape

(10, 3)

In [34]:
pandas_dataframe.shape

(2, 2)

In [35]:
numpy_array.shape

(3, 2)

In [36]:
gaussian_weights(T,params=gaussian_params).shape

NameError: name 'T' is not defined

In [37]:
param_a= np.array([[2, 6], [8, 12]])
param_b= np.array([[5, 9], [10, 7]])

In [38]:
gaussian_weights(param_a, params=gaussian_params)

TypeError: only size-1 arrays can be converted to Python scalars

In [41]:
c1= np.divide(1, np.sqrt(2 * np.math.pi * 1000))
print(c1)

0.012615662610100801


In [43]:
c2 = np.divide(-1, 2 * 1000)
print(c2)

-0.0005


In [58]:
sqdiffs = toeplitz(np.arange(Test_dl)) ** 2
print(sqdiffs)

[[ 0  1  4  9 16 25 36 49 64 81]
 [ 1  0  1  4  9 16 25 36 49 64]
 [ 4  1  0  1  4  9 16 25 36 49]
 [ 9  4  1  0  1  4  9 16 25 36]
 [16  9  4  1  0  1  4  9 16 25]
 [25 16  9  4  1  0  1  4  9 16]
 [36 25 16  9  4  1  0  1  4  9]
 [49 36 25 16  9  4  1  0  1  4]
 [64 49 36 25 16  9  4  1  0  1]
 [81 64 49 36 25 16  9  4  1  0]]


In [59]:
c3= 0.012615662610100801*np.exp(-0.0005*sqdiffs)
print (c3)

[[0.01261566 0.01260936 0.01259046 0.01255902 0.01251514 0.01245895
  0.01239061 0.01231033 0.01221835 0.01211494]
 [0.01260936 0.01261566 0.01260936 0.01259046 0.01255902 0.01251514
  0.01245895 0.01239061 0.01231033 0.01221835]
 [0.01259046 0.01260936 0.01261566 0.01260936 0.01259046 0.01255902
  0.01251514 0.01245895 0.01239061 0.01231033]
 [0.01255902 0.01259046 0.01260936 0.01261566 0.01260936 0.01259046
  0.01255902 0.01251514 0.01245895 0.01239061]
 [0.01251514 0.01255902 0.01259046 0.01260936 0.01261566 0.01260936
  0.01259046 0.01255902 0.01251514 0.01245895]
 [0.01245895 0.01251514 0.01255902 0.01259046 0.01260936 0.01261566
  0.01260936 0.01259046 0.01255902 0.01251514]
 [0.01239061 0.01245895 0.01251514 0.01255902 0.01259046 0.01260936
  0.01261566 0.01260936 0.01259046 0.01255902]
 [0.01231033 0.01239061 0.01245895 0.01251514 0.01255902 0.01259046
  0.01260936 0.01261566 0.01260936 0.01259046]
 [0.01221835 0.01231033 0.01239061 0.01245895 0.01251514 0.01255902
  0.01259046

In [60]:
print(Test_dl)

10


In [61]:
print(data_dl)

[array([[ 0.6679065 ,  1.01412835,  1.70973112],
       [-1.82276485,  0.43259722,  0.43744466],
       [-1.03065766,  1.50860989, -0.04874895],
       [ 0.44194384,  1.01343637, -0.7104585 ],
       [-0.58961348,  1.51557615,  2.07088696],
       [-1.28900542,  0.04583496, -0.01049901],
       [-0.39408823, -0.316129  , -0.45261595],
       [-0.83960616,  0.16359807, -1.1544791 ],
       [ 1.824592  , -0.26923179, -1.01808112],
       [ 1.67349299,  0.02313231, -0.36324252]])]
